
services:
  db:
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    environment:
      - POSTGRES_DB=weather_db
      - POSTGRES_USER=weather_user
      - SHARED_BUFFERS=1GB
      - EFFECTIVE_CACHE_SIZE=3GB
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/backup:/backup
    restart: unless-stopped