
services:
  db:
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    environment:
      - POSTGRES_DB=weather_db
      - POSTGRES_USER=weather_user
      - POSTGRES_DB=weather_db
      - POSTGRES_USER=weather_user
      - POSTGRES_SHARED_BUFFERS=512MB #1GB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=1GB #3GB
      - POSTGRES_MAINTENANCE_WORK_MEM=256MB #256MB
      - POSTGRES_WORK_MEM=32MB #64MB
      - POSTGRES_WAL_BUFFERS=16MB
      - POSTGRES_RANDOM_PAGE_COST=1.1
      - POSTGRES_SYNCHRONOUS_COMMIT=off
      - POSTGRES_MAX_PARALLEL_WORKERS=2 #4
      - POSTGRES_MAX_PARALLEL_WORKERS_PER_GATHER=1 #2
      - POSTGRES_MAX_PARALLEL_MAINTENANCE_WORKERS=1 #2
      - POSTGRES_AUTOVACUUM_MAX_WORKERS=2 #3
      - POSTGRES_AUTOVACUUM_VACUUM_SCALE_FACTOR=0.01
      - POSTGRES_AUTOVACUUM_VACUUM_THRESHOLD=5000
      - POSTGRES_MAX_CONNECTIONS=50
      - POSTGRES_STATEMENT_TIMEOUT=600000
      - POSTGRES_IDLE_IN_TRANSACTION_SESSION_TIMEOUT=60000
    shm_size: 512mb #1gb
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/backup:/backup
    restart: unless-stopped