name: Deploy backend (main branch) to PROD

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH > Pull backend from main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DIGITALOCEAN_SSHKEY }}  # Your SSH private key stored as a secret
          DROPLET_IP: ${{ secrets.DIGITALOCEAN_IP }}
        run: |
          echo "$SSH_PRIVATE_KEY" > id_rsa
          chmod 600 id_rsa
          ssh -i id_rsa -o StrictHostKeyChecking=no root@$DROPLET_IP "cd /var/www/rovis/backend/ && git fetch origin && git checkout main && git pull origin main && pm2 restart all --update-env"
          rm id_rsa
